name: Generate REAME.md File

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Install deno
        run: curl -fsSL https://deno.land/x/install/install.sh | sh && sudo ln -s $HOME/.deno/bin/deno /usr/local/bin/deno

      - name: Generate README
        run: deno run --allow-write --allow-net generate.ts

      - name: Commit README
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "Update README"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
